# Generated by Django 5.0.6 on 2026-03-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=15)),
                ('no_maquina', models.CharField(max_length=20)),
                ('falla_observacion', models.TextField()),
                ('atencion_prestada', models.TextField(blank=True, null=True)),
                ('encargado_lab', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.BooleanField(default=False)),
                ('ciclo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.cicloescolar')),
            ],
        ),
    ]
