# Generated by Django 4.0 on 2026-03-04 14:18

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=15)),
                ('no_maquina', models.CharField(max_length=20)),
                ('falla_observacion', models.TextField()),
                ('atencion_prestada', models.TextField(blank=True, null=True)),
                ('encargado_lab', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus', models.BooleanField(default=False)),
                ('ciclo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.cicloescolar')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
